# Generated by Django 3.0.3 on 2020-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200327_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('intent_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rasalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
